## [ Excel => DataFrame 저장 다루기]

(1) 모듈 로딩 <hr>

In [2]:
import pandas as pd

(2) 데이터 준비 <hr>

In [3]:
file1 = '../DATA/Single Worksheet.xlsx'
file2 = '../DATA/Multiple Worksheets.xlsx'

(3) EXCEL => DataFrame 저장하기

In [4]:
pd.read_excel(file1, header = None, usecols = [1,3], index_col = 1)
#파일을 불러옴
#컬럼명은 설정하지 않음
#1번,3번 컬럼만 씀
#1번 컬럼을 인덱스로 설정함

                1
3
Gender  Last Name
M           James
M         Hawkins
F             Day
F            Ruiz
F           Gomez

In [5]:
pd.read_excel(file2)

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [6]:
pd.read_excel(file2, sheet_name = 2 )            #3번째 시트 불러옴 (0번부터 시작)

  First Name  Last Name     City Gender
0     Robert     Miller  Seattle      M
1       Tara     Garcia  Phoenix      F
2    Raphael  Rodriguez  Orlando      M

In [7]:
pd.read_excel(file2, sheet_name = 'Data 3' )      #3번째 시트 불러옴 (시트명으로 불러옴)

  First Name  Last Name     City Gender
0     Robert     Miller  Seattle      M
1       Tara     Garcia  Phoenix      F
2    Raphael  Rodriguez  Orlando      M

In [8]:
# pd.read_excel(file2, sheet_name = None)          #모든걸 가져오는데 딕셔너리의 형태로 가져온다.

{'Data 1':   First Name Last Name           City Gender
 0    Brandon     James          Miami      M
 1       Sean   Hawkins         Denver      M
 2       Judy       Day    Los Angeles      F
 3     Ashley      Ruiz  San Francisco      F
 4  Stephanie     Gomez       Portland      F,
 'Data 2':   First Name Last Name           City Gender
 0     Parker     Power        Raleigh      F
 1    Preston  Prescott   Philadelphia      F
 2    Ronaldo   Donaldo         Bangor      M
 3      Megan   Stiller  San Francisco      M
 4     Bustin    Jieber         Austin      F,
 'Data 3':   First Name  Last Name     City Gender
 0     Robert     Miller  Seattle      M
 1       Tara     Garcia  Phoenix      F
 2    Raphael  Rodriguez  Orlando      M}

## [JSON ==> DataFrame 저장하기]

(1) 데이터 준비

In [9]:
file3 = '../DATA/nobel.json'

(2) JSON ==> DataFrame으로 저장

In [10]:
nobelDF = pd.read_json(file3)
nobelDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646 entries, 0 to 645
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   prizes  646 non-null    object
dtypes: object(1)
memory usage: 5.2+ KB

(3) 데이터 확인

In [11]:
print(nobelDF.head(3), nobelDF.tail(3), sep='\n\n')

                                              prizes
0  {'year': '2019', 'category': 'chemistry', 'lau...
1  {'year': '2019', 'category': 'economics', 'lau...
2  {'year': '2019', 'category': 'literature', 'la...

                                                prizes
643  {'year': '1901', 'category': 'peace', 'laureat...
644  {'year': '1901', 'category': 'physics', 'laure...
645  {'year': '1901', 'category': 'medicine', 'laur...

(4) 데이터 추출

In [12]:
# 행 추출 => iloc[] / loc[]
nobelDF.iloc[0]                #행 1줄을 뺐다. 뺀거는 시리즈의 형태

prizes    {'year': '2019', 'category': 'chemistry', 'lau...
Name: 0, dtype: object

In [13]:
nobelDF.iloc[0]['prizes']      #행 1줄을 뺀 상태에서 레이블을 불러서 데이터를 불렀다. 그것은 딕셔너리의 형태

{'year': '2019',
 'category': 'chemistry',
 'laureates': [{'id': '976',
   'firstname': 'John',
   'surname': 'Goodenough',
   'motivation': '"for the development of lithium-ion batteries"',
   'share': '3'},
  {'id': '977',
   'firstname': 'M. Stanley',
   'surname': 'Whittingham',
   'motivation': '"for the development of lithium-ion batteries"',
   'share': '3'},
  {'id': '978',
   'firstname': 'Akira',
   'surname': 'Yoshino',
   'motivation': '"for the development of lithium-ion batteries"',
   'share': '3'}]}

In [14]:
# 행 추출 => iloc[[n1, ... ,]]/loc[]
nobelDF.iloc[[0,3]]

                                              prizes
0  {'year': '2019', 'category': 'chemistry', 'lau...
3  {'year': '2019', 'category': 'peace', 'laureat...

In [15]:
oneData =  nobelDF.iloc[0]['prizes']
type(oneData)

dict

In [16]:
#oneData가 딕셔너리 형태니까 아래와 같이 접근 가능하다.
print(oneData.keys(), oneData.items(), sep='\n\n')

dict_keys(['year', 'category', 'laureates'])

dict_items([('year', '2019'), ('category', 'chemistry'), ('laureates', [{'id': '976', 'firstname': 'John', 'surname': 'Goodenough', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '977', 'firstname': 'M. Stanley', 'surname': 'Whittingham', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '978', 'firstname': 'Akira', 'surname': 'Yoshino', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}])])

In [17]:
for k, v in oneData.items():
    print(f'[{k}] \n===> {v}')
    print()
    if k == 'laureates':
        for d in v:            # 여기서 v는 dict 원소로 구성된 list
            for k1, v1 in d.items():
                print("-", k1, v1)

[year]
===> 2019

[category]
===> chemistry

[laureates]
===> [{'id': '976', 'firstname': 'John', 'surname': 'Goodenough', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '977', 'firstname': 'M. Stanley', 'surname': 'Whittingham', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '978', 'firstname': 'Akira', 'surname': 'Yoshino', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}]

- id 976
- firstname John
- surname Goodenough
- motivation "for the development of lithium-ion batteries"
- share 3
- id 977
- firstname M. Stanley
- surname Whittingham
- motivation "for the development of lithium-ion batteries"
- share 3
- id 978
- firstname Akira
- surname Yoshino
- motivation "for the development of lithium-ion batteries"
- share 3

- json  중첩 데이터의 다중 반복문 ==> 단일 리스트 형태 처리 : 평탄화 / 정규화

In [18]:
pd.json_normalize(oneData)
# 여기서 'laureates'에서 각 아이디를 컬럼명으로 하고 그 밸류를 데이터로 하기위해 아래와 같이 함

   year   category                                          laureates
0  2019  chemistry  [{'id': '976', 'firstname': 'John', 'surname':...

In [19]:
pd.json_normalize(oneData, record_path='laureates')
#어떤 완벽한 데이터를 레코드로 하여 데이터 프레임으로 뽑을거냐 => record_path

,id,firstname,surname,motivation,share
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3

In [20]:
pd.json_normalize(oneData, record_path='laureates', meta=["year", "category"])
# meta 변수지정을 통해 시라졌던 year, category가 컬럼명에 추가되었다.

#이렇듯 늘 데이터 원본을 먼저 보아야 무엇을 제어하고 다루어야할지 보인다. 무턱대로 부르면 ㄴㄴ

,id,firstname,surname,motivation,share,year,category
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3,2019,chemistry
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3,2019,chemistry
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3,2019,chemistry

- 모든 행에 대한 정규화/평탄화 진행

In [21]:
# 컬럼 읽기 => DF객체변수명['컬럼명'], DF객체변수명.컬럼명
# ===> 모든 행에 record_path에 해당하는 키(key)가 존재해야함 
# ===> 없는 행에 record_path에 해당하는 키(key) 추가

#pd.json_normalize(nobelDF.prizes, record_path='laureates')
#KeyError 발생: "Key 'laureates' not found.

for data in nobelDF.prizes:
    print(type(data), data.keys(), end='\n\n')
    # 해당 dict에 laureates 키가 없다면 추가
    data.setdefault('laureates', [])                  #기본값을 설정하여 없다면 저렇게 빈리스트 설정해줌

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])


In [22]:
nobelDF2 = pd.json_normalize(nobelDF.prizes, record_path='laureates', meta = ['year', 'category'])
# 위에서 없는거는 만들어놓았기때문에 더이상 keyError ㄴㄴ

nobelDF2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          950 non-null    object
 1   firstname   950 non-null    object
 2   surname     921 non-null    object
 3   motivation  950 non-null    object
 4   share       950 non-null    object
 5   year        950 non-null    object
 6   category    950 non-null    object
dtypes: object(7)
memory usage: 52.1+ KB

(7) JSON의 다양한 방식의 DataFrame 저장하기 => orient 파라미터

In [23]:
json_data='''
[
{"id" : "1","name":"sravan","age":22},
{"id" : "2","name":"harsha","age":22},
{"id" : "3","name":"deepika","age":21},
{"id" : "4","name":"jyothika","age":23}
]
'''

- orient = 'record' 설정 => JSON 파일 데이터를 행 단위로 읽어서 DataFrame에 저장

In [24]:
df = pd.read_json(json_data, orient = 'records')
# 딕셔너리 속 키가 컬럼명이 되고 밸류가 데이터가 된다.
print(df)

   id      name  age
0   1    sravan   22
1   2    harsha   22
2   3   deepika   21
3   4  jyothika   23

In [25]:
# 데이터 => 키 : {값}
json_data2 = '''
{
    "student-1" : {"id" : "1","name":"sravan","age":22},
    "student-2" : {"id" : "2","name":"harsha","age":22},
    "student-3" : {"id" : "3","name":"deepika","age":21},
    "student-4" : {"id" : "4","name":"jyothika","age":23}

}
'''

In [26]:
df2 = pd.read_json(json_data2, orient = 'index')
# 키를 인덱스명으로 지정함 (orient의 default는 column)
# 키가 인덱스 레이블이 되고, 밸류속 키와 밸류는 컬럼명과 데이터가 된다.
print(df2)

           id      name  age
student-1   1    sravan   22
student-2   2    harsha   22
student-3   3   deepika   21
student-4   4  jyothika   23

In [27]:
df2 = pd.read_json(json_data2).T
# 디폴트로는 오리엔트가 컬럼인데 여기에 T 메소드를 주면 인덱스와 컬럼이 서로 바뀐다.
print(df2)

          id      name age
student-1  1    sravan  22
student-2  2    harsha  22
student-3  3   deepika  21
student-4  4  jyothika  23

In [28]:
# JSON Format 
json_data3 = '''
[
    [ "1", "sravan",22 ],
    [ "2", "harsha",22 ],
    [ "3", "deepika",21 ],
    [ "4", "jyothika",23 ]
]
'''

# 키가 없고 값만 존재하고있음

In [29]:
df = pd.read_json(json_data3)     #orient = 'values'
print(df)
# 1개의 레코드가 1개의 행으로 들어감

   0         1   2
0  1    sravan  22
1  2    harsha  22
2  3   deepika  21
3  4  jyothika  23